version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ledgerflow-postgres
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
      POSTGRES_DB: mini_wallet
    ports:
      - "5454:5432"

  redis:
    image: redis:7-alpine
    container_name: ledgerflow-redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ledgerflow-kafka
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"

  ledgerflow-app:
    build: .
    container_name: ledgerflow-api
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mini_wallet
      - SPRING_DATASOURCE_USERNAME=wallet_user
      - SPRING_DATASOURCE_PASSWORD=wallet_password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_REDIS_HOST=redis